### ISSUE TITLE
Translation of Links broken

### ISSUE THREAD

**Issue by sebastianSchmidt86** [humhub/translator-issues#10]
How to reproduce:
- Create a post entry with a link and also set a link title
- The post will be created as `Test message with [Link](https://www.google.at "Link")`
- If you now translate this post you will get the following in the translation_cache table: `Testmeldung mit [Link](https://www.google.at &quot;Link&quot;)`

the translation looks like this in the frontend:
<img width="364" alt="image" src="https://github.com/humhub/translator-issues/assets/941711/84cc7ea0-a141-4c1f-ac68-8201c23fde06">

Expected behaviour is this:
<img width="265" alt="image" src="https://github.com/humhub/translator-issues/assets/941711/93eec45d-1edd-43a7-9578-8da048dd2b05">

**Comment by luke-** [comment]
@sebastianSchmidt86 Do I understand correctly that the problem is that the DeepL API returns encoded quotes?

Maybe there is an option that DeepL does not encode here?

**Comment by sebastianSchmidt86** [comment]
I just saw that the original text is stored with encoded quotes and is being sent to DeepL/Google incorrectly.

Instead of
`Test message with [Link](https://www.google.at "Link")`
this is sent to Deepl/Google
`Test message with [Link](https://www.google.at &quot;Link&quot;)`

Maybe we should use `$event->sender->text` instead of `$event->sender->content` in `Events.php`

**Comment by yurabakhtin** [comment]
@sebastianSchmidt86 @luke- I see a difference between `$event->sender->text` and `$event->sender->content` here https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/widgets/richtext/ProsemirrorRichText.php#L143-L148 so the `content` may has some preparations from extenssions side, so I have decided to keep it there but added `Html::decode()`.
PR https://github.com/humhub/translator/pull/40.
