### ISSUE TITLE
The translation text is hidden until the "read more" button is clicked

### ISSUE THREAD

**Issue by marc-farre** [humhub/translator-issues#2]
Create a post with a very long text.
As the text is too long, you need to click on " Read more" to see the full text.
If you don't click on "Read more", but on the "Translate" button, the user only see the "Translate" button disappearing, but nothing else.
He need to click on "Read more" to see that in fact the translation exists, at the end of the text.

**Comment by atdqm** [comment]
Do you think a solution can be found ?

**Comment by luke-** [comment]
Hmm, maybe we can fix this using Javascript in such situation. @yurabakhtin Can you please take a look?

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/translator/pull/22.
