### ISSUE TITLE
Changing original text into another language gives the translation of the original text

### ISSUE THREAD

**Issue by marc-farre** [humhub/translator-issues#3]
Steps to reproduce:
1. Set your account to the French language
2. Write a french text, e.g.: `test de publication`
3. Edit the post text and replace the french text with an English text, e.g.: `another text completely different in English`
4. Click on "translate"
5. The translate text is `test de publication`

![image](https://user-images.githubusercontent.com/23310825/191599795-a77d6bb7-de91-415e-abd0-0dadfb2df64f.png)

I didn't take time to search for the reason of this bug, but I found another bug that occurs for all translated text, and that might explain this problem:

In the `TranslateController`, when `RichTextTranslation::output($fixedTranslation)` is triggered, the translated message is intercepted again by the Event, and added as new line to the `translator_cache` table with `orginial` set to `1`.

This line is useless in the database, and might be the source of this bug.

**Comment by luke-** [comment]
Hmm, I cannot reproduce this.

**Comment by marc-farre** [comment]
Well, I can't reproduce either!
I close the issue and will reopen it if the problem occurs again later.
Thanks for having tried!
