### ISSUE TITLE
Configure the number of characters/words sent for language detection

### ISSUE THREAD

**Issue by sebastianSchmidt86** [humhub/translator-issues#6]
It would be great if we can configure the max number of characters/words which will be sent to Google for the language detection.
For really long texts/posts the current implementation consumes our quota unnecessarily.

**Comment by luke-** [comment]
It should be sufficient here to have a variable in the module class in which a value of e.g. 200 is set by default.  If necessary, this can be changed via the configuration file.

**Comment by luke-** [comment]
Available with 1.2.2
